services:
    api:
      build:
        context: ../kyotei-api
        dockerfile: ../kyotei-deploy/api/Dockerfile
      volumes:
        - ../kyotei-api:/api
      ports:
        - "${API_PORT}:8000"
      networks:
        - kyotei_api_network

    webapp:
      build:
        context: ../kyotei-webapp
        dockerfile: ../kyotei-deploy/webapp/Dockerfile
      volumes:
        - ../kyotei-webapp:/webapp
        - webapp-node-modules:/webapp/node_modules
      ports:
        - "${WEBAPP_PORT}:5173"
      networks:
        - kyotei_webapp_network
        - kyotei_api_network

    webapp-db:
      image: postgres:17
      container_name: kyotei_webapp_db
      restart: unless-stopped
      environment:
        POSTGRES_USER: ${WEBAPP_DB_USER}
        POSTGRES_PASSWORD: ${WEBAPP_DB_PASSWORD}
        POSTGRES_DB: ${WEBAPP_DB_NAME}
      ports:
        - "${WEBAPP_DB_PORT}:5432"
      volumes:
        - webapp-db-vol:/var/lib/postgresql/data
      networks:
        - kyotei_webapp_network

    api-db:
      image: postgres:17
      container_name: kyotei_api_db
      restart: unless-stopped
      environment:
        POSTGRES_USER: ${API_DB_USER}
        POSTGRES_PASSWORD: ${API_DB_PASSWORD}
        POSTGRES_DB: ${API_DB_NAME}
      ports:
        - "${API_DB_PORT}:5432"
      volumes:
        - api-db-vol:/var/lib/postgresql/data
      networks:
        - kyotei_api_network

networks:
  kyotei_webapp_network: {}
  kyotei_api_network: {}

volumes:
  api-db-vol:
  webapp-db-vol:
  webapp-node-modules:

